# Generated by Django 3.2.12 on 2022-03-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('species', models.IntegerField(choices=[(1, 'dog'), (2, 'cat'), (3, 'rabit'), (4, 'horse'), (5, 'bird'), (6, 'goat'), (6, 'cow')])),
                ('health', models.IntegerField(choices=[(1, 'healthy'), (2, 'chronically sick'), (3, 'seriously ill'), (4, 'during treatment'), (5, 'moribund')])),
                ('status', models.IntegerField(choices=[(1, 'waiting for adoption'), (2, 'in the middle of trying to adopt'), (3, 'not to adoption'), (4, 'adopted')])),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.IntegerField(choices=[(1, 'emergency animal feed'), (2, 'animal feed')])),
                ('stan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=120)),
                ('specialization', models.IntegerField(choices=[(1, 'pets permitted'), (2, 'exotic pets'), (3, 'livestock')])),
                ('animals', models.ManyToManyField(blank=True, to='AnimalsTeam.Animals')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=120)),
                ('role', models.IntegerField(choices=[(1, 'inspektor'), (2, 'volunteer')])),
                ('join_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('animals', models.ManyToManyField(blank=True, to='AnimalsTeam.Animals')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'in the middle of trying to adopt'), (2, 'adopted')])),
                ('date_adoption', models.DateField()),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalsTeam.adopter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalsTeam.animals')),
            ],
        ),
        migrations.AddField(
            model_name='adopter',
            name='animal',
            field=models.ManyToManyField(blank=True, to='AnimalsTeam.Animals'),
        ),
        migrations.AddField(
            model_name='adopter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
