# Generated by Django 3.2.12 on 2022-03-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalsTeam', '0004_remove_adoption_date_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalsTeam.personel'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='role',
            field=models.IntegerField(choices=[(1, 'inspektor'), (2, 'volunteer'), (3, 'adopter')]),
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
    ]
