# Generated by Django 3.2.12 on 2022-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalsTeam', '0005_auto_20220317_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='role',
            field=models.IntegerField(choices=[(1, 'adopter'), (2, 'volunteer')]),
        ),
    ]
